### ISSUE TITLE
Example code for reAnalyzeURL fails with TypeError: callback is not a function

### ISSUE THREAD

**Issue by mrowell** [natewatson999/node-virustotal#16]
When running the example code for [reAnalyzeURL](https://github.com/natewatson999/node-virustotal#v3reanalyzeurl) it fails with `TypeError: callback is not a function`

```
/Users/node/Documents/node_modules/node-virustotal/v3.js:120
			callback(body);
			^

TypeError: callback is not a function
    at Request._callback (/Users/node/Documents/node_modules/node-virustotal/v3.js:120:4)
    at Request.self.callback (/Users/node/Documents/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/Users/node/Documents/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/Users/node/Documents/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

Is this example expected to work as is or am I missing something?

**Comment by natewatson999** [comment]
I'll take a look. That's not supposed to happen.

**Comment by Shroototem** [comment]
Same issue with "reAnalyzeFile".

**Comment by natewatson999** [comment]
I just pushed a patch that should fix the issue. Bear in mind that you have to use the URL ID. LMK if you encounter any other bugs with it or if you need it working with something other than the IDs.
